### ISSUE TITLE
[Feature request] date time range 

### ISSUE THREAD

**Issue by ksn135** [symfony2admingenerator/FormExtensionsBundle#15]
May be we should add this (https://github.com/dangrossman/bootstrap-daterangepicker) ?

**Comment by loostro** [comment]
@ksn135 just merged on master... right now testing diffrent configuration

**Comment by ksn135** [comment]
@loostro :+1:

**Comment by loostro** [comment]
As of `v2.0-beta.13` tag, the `s2a_daterange_picker` is avaliable. Please note, that passing parameters like `moment().add(29, 'days').startOf('month')` is supported, but requires [FormBundle](https://github.com/symfony2admingenerator/FormBundle) `>= v1.2.1` (the `1.2` minor update fixed `e4js` to allow recognizing chained JS function calls).

**Comment by loostro** [comment]
Another note: there are new bundle configuration like `admingenerator_form_extensions.include_momentjs`. By default they are all set to `false`. You must either set it to `true` or include JS dependencies manually.
