### ISSUE TITLE
Double choice field

### ISSUE THREAD

**Issue by bobvandevijver** [symfony2admingenerator/FormExtensionsBundle#17]
I noticed that this bundle includes two form types for the a choice field, which are essentially the same: s2_select2_choice and choice. 

In short:
s2a_select2_choice: uses [ivaynberg/select2](https://github.com/ivaynberg/select2)
choice: uses [bootstrap-select](http://silviomoreto.github.io/bootstrap-select)

I think that, for the sake of simplicity, it is easier and neater to remove the choice overwrite, so that this bundle only uses widgets in the `s2a_` namespace.

@loostro, @sescandell: What are your thoughts on this?

If you do not think this is handy (probably because of the admingenerator), can you propose any method to exclude a specific field from this behaviour? If none exists, maybe adding a data-{something} attribute to the field to exclude might be an option?

**Comment by loostro** [comment]
No, they are diffrent as their purpose is diffrent.

## BootstrapSelectExtension

This is just an enxtension to the default choice type.

The goal of `bootstrap-select` is to enhance the "visual" part of choice field when it is rendered as select tag. The default select tag is ugly and impossible to style with CSS. This widget hides the select tag and instead displays a "boostrap styled" dropdown list. However - it does not have any extra functionalities. It's just visual enhancement.

## Select2Type

This is a completely new form type.

The goal of `ivaynberg/select2` is to introduce new functionality:
* searching/filtering choices
* possible AJAX data loading
* possible infinite scrolling
* possible styling each choice (displaying images, HTML content, see image below)
![demo s2](https://cloud.githubusercontent.com/assets/1419884/5898257/f402fbe8-a54d-11e4-8fc2-7696811822c9.png)
* and many more...

So, I do not believe that either is redundant.

**Comment by bobvandevijver** [comment]
Ok, I see that now, but I have troubles with the Choice extension for a specific field. Do you know a way to disable it for that specific field?

**Comment by loostro** [comment]
I've created a PR which should resolve this problem. Please review if I have not made any careless mistakes :)

**Comment by bobvandevijver** [comment]
Closed, as #18 fixes this :)
