### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by tobias-93** [symfony2admingenerator/FormExtensionsBundle#33]
jQuery is now fixed on a quite old version (1.9.1), while version 1.11.2 is already published for a few months.
This fixation makes upgrading to the newest jQuery impossible.
In the latest Firefox, there are already some features that do not work anymore.
Could you remove this fixation to make upgrading possible?

**Comment by loostro** [comment]
@tobias-93 I'm not sure all the widgets will work with jquery 1.11. This requires testing.

**Comment by tobias-93** [comment]
@loostro sure, this wast just to let you know. Workaround is of course to use a different browser.

**Comment by loostro** [comment]
@tobias-93 the js files in [public/vendor/jquery/js](https://github.com/symfony2admingenerator/FormExtensionsBundle/tree/master/Resources/public/vendor/jquery/js) are jquery v1.11.2

**Comment by tobias-93** [comment]
Could you then remove the dependency on jquery in total? Some of our dependencies do use the components/jquery version, which is fixed due to the fixation in the formextensionsbundle...

**Comment by loostro** [comment]
@tobias-93 use the [`admingenerator_form_extensions.include_jquery`](https://github.com/symfony2admingenerator/FormExtensionsBundle/blob/master/DependencyInjection/Configuration.php#L41) parameter to decide if it's included by the bundle

if you set it to false, you have to include it manually (on pages that use FormExtensions, as they all use jQuery)

the good news is **probably** any version 1.6+ will work, at least our javascript code only uses basic selectors `$(document).ready({ /* init code */ })`, some of the external libraries we use may depend on some parts of newer jQuery version, but I have not tested all, so I can't really tell..

**Comment by tobias-93** [comment]
@loostro I meant the reference to jQuery in the composer.json which is no longer needed since jQuery is now included in the bundle assets. I understand how to use the bundled version, thank you.
