### ISSUE TITLE
Feature, add support to bower

### ISSUE THREAD

**Issue by kuldipem** [symfony2admingenerator/FormExtensionsBundle#37]
I think, bower in widely used to install or manage assets. We can add `bower.json` and `.bowerrc` to support installation versions of assets and directory where assets will be installed, respectively .

**Comment by loostro** [comment]
We already have the assets handled by composer. Changeing to bower would only add another dependency, which is unnecessary.

**Comment by sescandell** [comment]
I think we should really think about bower (as in the GeneratorBundle). In my opinion, managins assets dependency through composer is not a good idea: it's not its purpose. Bower is here for that...

I think we really should think about it...

**Comment by kuldipem** [comment]
ya @sescandell  bower is common to install and manage static assets.
