### ISSUE TITLE
dev-master w. SF2.7

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/FormExtensionsBundle#55]
I'm using SF2.7, but got this error when I'm trying to upgrade lib with "dev-master" tag:

```
  Problem 1
    - Installation request for symfony2admingenerator/form-extensions-bundle dev-master -> satisfiable by symfony2admingenerator/form-extensions-bundle[dev-master].
    - symfony2admingenerator/form-extensions-bundle dev-master requires symfony/symfony ~2.8|~3.0 -> no matching package found.
```

The dev-master is not compatible with the SF2.7 version?

**Comment by bobvandevijver** [comment]
That is correct, we dropped support for Symfony <2.8.

**Comment by Lionel09** [comment]
ok thanks
I feel annoyed you dropped the support of an LTS version.

**Comment by Lionel09** [comment]
so at least it will be a good reason for me to migrate to 2.8 :)

BTW, the doc needs a little upgrade too:

For Symfony version lower than **2.8** or Twig lower than 1.12 add the following to your composer.json:

**Comment by bobvandevijver** [comment]
@Lionel09 This bundle is still not stable, so we choose to support the latest LTS, which is 2.8. The doc will be updated and that notice will be removed with my PR.
