### ISSUE TITLE
Could not load type "s2a_daterange_picker"

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/FormExtensionsBundle#56]
Env: SF2.8

After updating my lib, I've got this error:

```Could not load type "s2a_daterange_picker in vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php at line 92" ```

Have I to change something with date range picker?
Thanks!

**Comment by tobias-93** [comment]
@Lionel09 you cannot refer to the form name anymore, you have to refer to the FQCN (so `Admingenator\FormExtensionsBundle\Form\Type\DaterangePickerType` or DaterangePickerType::class for PHP > 5.4)

**Comment by bobvandevijver** [comment]
@Lionel09: You can also ask such simple question in our [Gitter channel](https://gitter.im/symfony2admingenerator/GeneratorBundle) instead of opening issues (which aren't issues).

**Comment by Lionel09** [comment]
Thanks for your responses, and sorry for disturbing

@bobvandevijver the advantage of opening an issue is that other people with same problem will not annoy you anymore with same question; btw, it's not always easy to know if it's an issue or not with - sometimes - outdated and/or minimalist documentation. But a big thanks again for your great works!

**Comment by pjam** [comment]
Yes, I was having the same problem with s2a_collection_upload. Got the solution here. Is good to have everything in the issues.
Please update the documentation when possible

**Comment by bobvandevijver** [comment]
@pjam You can always create an PR to update the docs for that :smiley: Would be appreciated!

**Comment by bobvandevijver** [comment]
@pjam You can always create an PR to update the docs for that :smiley: Would be appreciated!
