### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'fileupload' of undefined

### ISSUE THREAD

**Issue by alexbaron** [symfony2admingenerator/FormExtensionsBundle#74]
hello,

after assetic:dump command in chrome console, i've got this error :
`
Uncaught TypeError: Cannot read property 'fileupload' of undefined
`
line 8 : 
`
;$.widget('blueimp.fileupload', $.blueimp.fileupload, {
`

Have you any solutions ?

**Comment by bobvandevijver** [comment]
It looks like you do not have the `blueimp` depency enabled. Check your configuration (see [this page](https://github.com/symfony2admingenerator/FormExtensionsBundle/blob/master/Resources/doc/documentation.md), specifically the `include_blueimp`). By default they are not included.

**Comment by bobvandevijver** [comment]
Closing due to no response and the solution should be clear.
